version: 2
jobs:
  test:
    docker:
      - image: circleci/node-browsers
    steps:
      - checkout
      - run: mkdir test-reports
      - run:
          name: Download Selenium
          command: |
            curl -O http://selenium-release.storage.googleapis.com/3.9/selenium-server-standalone-3.9.1.jar
      - run:
          name: Start Selenium
          command: |
            java -jar selenium-server-standalone-3.9.1.jar -log test-reports/selenium.log
          background: true

      - run:
          command: |
        #run tests      
        #PRODUCTION_URL

      - store_artifacts:
          path: test-reports/
          destination: tr1
      - store_test_results:
          path: test-reports/


workflows:
   version: 2
   commit:
     jobs:
       - test
   nightly:
     triggers:
       - schedule:
           cron: "0 0 * * *"
           filters:
             branches:
               only:
                 - master

